AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: nuevoUsuario

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

  UserPolicyAttachment:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AccesoS3
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:*"
            Resource: "*"
      Users:
        - !Ref IAMUser

Outputs:
  AccessKeyId:
    Description: "ID de la Clave de Acceso para el usuario IAM"
    Value: !Ref AccessKey

  SecretAccessKey:
    Description: "Clave Secreta de Acceso para el usuario IAM"
    Value: !GetAtt AccessKey.SecretAccessKey
